import type { JobOrder, Candidate, Comment } from '@/types/recruitment'

// Use UI Avatars API as fallback — generates initials avatars from any name
const avatar = (name: string) =>
  `https://ui-avatars.com/api/?name=${encodeURIComponent(name)}&background=303030&color=fff&bold=true&size=128`

// ============================================
// Mock Job Orders (extended with detail fields)
// ============================================

export const mockJobOrders: JobOrder[] = [
  {
    id: '1',
    title: 'Backend Developer',
    department: 'Engineering',
    level: 'Senior',
    count: 2,
    status: 'approved',
    requestCode: 'REQ-20260703-001',
    requesterName: 'Nguyễn Văn An',
    requesterAvatar: avatar('Nguyễn Văn An'),
    requestDate: '03/07/2026',
    requestTime: '16:57',
    recruitmentReason:
      'Mở rộng đội ngũ phát triển sản phẩm mới nhằm phục vụ thị trường Đông Nam Á.',
    requiredSkills: ['Java', 'Spring Boot', 'PostgreSQL', 'AWS'],
    workArrangement: 'Hybrid (3 ngày tại văn phòng)',
    budget: '30 - 45 triệu/tháng',
    description:
      'Chúng tôi đang tìm kiếm một Backend Developer tài năng để gia nhập đội ngũ Engineering. Bạn sẽ chịu trách nhiệm thiết kế và phát triển các hệ thống backend scalable, làm việc với microservices và các giải pháp cloud-native.',
    requirements: [
      'Tối thiểu 4 năm kinh nghiệm Backend với Node.js, Go hoặc Java',
      'Thành thạo PostgreSQL, Redis, Kafka',
      'Kinh nghiệm với AWS/GCP, Docker, Kubernetes',
      'Hiểu biết về microservices architecture và event-driven systems',
      'Khả năng code review và mentoring junior devs',
    ],
    benefits: [
      'Lương cạnh tranh + thưởng KPI theo quý',
      'Bảo hiểm sức khỏe cao cấp cho cả gia đình',
      '20 ngày phép có lương / năm',
      'Budget học tập & conference 15 triệu / năm',
      'Macbook Pro + màn hình 4K',
    ],
    location: 'Hà Nội',
    workType: 'Hybrid',
    salaryMin: 40,
    salaryMax: 65,
    salaryCurrency: 'triệu',
    deadline: '31/07/2026',
    hiringManager: {
      name: 'Trần Quốc Bảo',
      title: 'Engineering Manager',
      avatar: avatar('Trần Quốc Bảo'),
    },
    skills: ['Node.js', 'PostgreSQL', 'Kubernetes', 'AWS', 'Microservices'],
    workflow: [
      {
        id: 'w1',
        title: 'Tạo yêu cầu',
        person: 'Nguyễn Văn An',
        personAvatar: avatar('Nguyễn Văn An'),
        status: 'done',
        statusLabel: 'Đã gửi',
        statusColor: 'success',
        relativeTime: '1 ngày trước',
        timestamp: '03/07/2026 16:53',
      },
      {
        id: 'w2',
        title: 'Trưởng bộ phận duyệt',
        person: 'Kevin Hoang',
        personAvatar: avatar('Kevin Hoang'),
        status: 'done',
        statusLabel: 'Đã duyệt',
        statusColor: 'success',
        relativeTime: '1 ngày trước',
        timestamp: '03/07/2026 16:57',
      },
      {
        id: 'w3',
        title: 'HR duyệt',
        person: 'Trần Thị Mai',
        personAvatar: avatar('Trần Thị Mai'),
        status: 'active',
        statusLabel: 'Đang chờ',
        statusColor: 'active',
        relativeTime: 'Hôm nay',
      },
      {
        id: 'w4',
        title: 'Hoàn tất',
        person: 'Hệ thống',
        personAvatar: '',
        status: 'pending',
        statusLabel: '',
        statusColor: 'outline',
      },
    ],
  },
  {
    id: '2',
    title: 'Product Designer',
    department: 'Product',
    level: 'Mid-level',
    count: 1,
    status: 'approved',
    requestCode: 'REQ-20260701-002',
    requesterName: 'Trần Thị Mai',
    requesterAvatar: avatar('Trần Thị Mai'),
    requestDate: '01/07/2026',
    requestTime: '10:24',
    recruitmentReason:
      'Cần bổ sung Product Designer để dẫn dắt thiết kế cho dòng sản phẩm B2B mới ra mắt Q3.',
    requiredSkills: ['Figma', 'Design System', 'Prototyping', 'User Research'],
    workArrangement: 'Hybrid (2 ngày tại văn phòng)',
    budget: '25 - 35 triệu/tháng',
    description:
      'Tìm kiếm Product Designer có tư duy sản phẩm mạnh để join team Product. Bạn sẽ thiết kế end-to-end trải nghiệm người dùng cho các tính năng mới, làm việc chặt chẽ với PM và Engineering.',
    requirements: [
      '3+ năm kinh nghiệm Product Design tại startup hoặc product company',
      'Portfolio thể hiện tư duy end-to-end (research → wireframe → hi-fi)',
      'Thành thạo Figma và prototyping tools',
      'Hiểu biết về design systems và Polaris / Material Design',
      'Khả năng giao tiếp tốt với stakeholders không chuyên',
    ],
    benefits: [
      'Lương 25-35 triệu tùy năng lực',
      'Flexible working hours',
      'Môi trường design-driven, có design system riêng',
      'Cơ hội tham gia conference thiết kế quốc tế',
    ],
    location: 'TP. Hồ Chí Minh',
    workType: 'Hybrid',
    salaryMin: 25,
    salaryMax: 35,
    salaryCurrency: 'triệu',
    deadline: '15/07/2026',
    hiringManager: {
      name: 'Lê Khánh Vy',
      title: 'Head of Product',
      avatar: avatar('Lê Khánh Vy'),
    },
    skills: ['Figma', 'Design System', 'Prototyping', 'User Research'],
    workflow: [
      {
        id: 'w1',
        title: 'Tạo yêu cầu',
        person: 'Trần Thị Mai',
        personAvatar: avatar('Trần Thị Mai'),
        status: 'done',
        statusLabel: 'Đã gửi',
        statusColor: 'success',
        relativeTime: '3 ngày trước',
        timestamp: '01/07/2026 10:24',
      },
      {
        id: 'w2',
        title: 'Trưởng bộ phận duyệt',
        person: 'Phạm Quang Hải',
        personAvatar: avatar('Phạm Quang Hải'),
        status: 'done',
        statusLabel: 'Đã duyệt',
        statusColor: 'success',
        relativeTime: '3 ngày trước',
        timestamp: '01/07/2026 14:08',
      },
      {
        id: 'w3',
        title: 'HR duyệt',
        person: 'Đỗ Thanh Tâm',
        personAvatar: avatar('Đỗ Thanh Tâm'),
        status: 'done',
        statusLabel: 'Đã duyệt',
        statusColor: 'success',
        relativeTime: '3 ngày trước',
        timestamp: '02/07/2026 09:15',
      },
      {
        id: 'w4',
        title: 'Hoàn tất',
        person: 'Hệ thống',
        personAvatar: '',
        status: 'done',
        statusLabel: 'Hoàn tất',
        statusColor: 'success',
        relativeTime: '2 ngày trước',
        timestamp: '02/07/2026 09:16',
      },
    ],
  },
  {
    id: '3',
    title: 'QA Engineer',
    department: 'Quality Assurance',
    level: 'Junior',
    count: 1,
    status: 'approved',
    requestCode: 'REQ-20260628-003',
    requesterName: 'Lê Minh Đức',
    requesterAvatar: avatar('Lê Minh Đức'),
    requestDate: '28/06/2026',
    requestTime: '09:12',
    recruitmentReason: 'Tăng cường đội ngũ QA cho dự án automation testing phase 2.',
    requiredSkills: ['Manual Testing', 'API Testing', 'SQL'],
    workArrangement: 'Onsite (tại văn phòng Đà Nẵng)',
    budget: '12 - 18 triệu/tháng',
    description:
      'Vị trí QA Engineer cho đội ngũ Quality Assurance. Phù hợp với bạn mới ra trường hoặc có 1-2 năm kinh nghiệm, muốn phát triển trong lĩnh vực automation testing.',
    requirements: [
      '0-2 năm kinh nghiệm QA (manual hoặc automation)',
      'Hiểu biết cơ bản về SQL, API testing (Postman)',
      'Có tư duy logic, chi tiết, cẩn thận',
      'Sẵn sàng học hỏi automation tools (Playwright/Cypress)',
    ],
    benefits: [
      'Lương khởi điểm 12-18 triệu',
      'Được đào tạo bài bản về automation testing',
      'Lộ trình thăng tiến rõ ràng',
    ],
    location: 'Đà Nẵng',
    workType: 'Onsite',
    salaryMin: 12,
    salaryMax: 18,
    salaryCurrency: 'triệu',
    deadline: '20/07/2026',
    hiringManager: {
      name: 'Phạm Thanh Hà',
      title: 'QA Lead',
      avatar: avatar('Phạm Thanh Hà'),
    },
    skills: ['Manual Testing', 'API Testing', 'SQL'],
    workflow: [
      {
        id: 'w1',
        title: 'Tạo yêu cầu',
        person: 'Lê Minh Đức',
        personAvatar: avatar('Lê Minh Đức'),
        status: 'done',
        statusLabel: 'Đã gửi',
        statusColor: 'success',
        relativeTime: '6 ngày trước',
        timestamp: '28/06/2026 09:12',
      },
      {
        id: 'w2',
        title: 'Trưởng bộ phận duyệt',
        person: 'Phạm Thanh Hà',
        personAvatar: avatar('Phạm Thanh Hà'),
        status: 'done',
        statusLabel: 'Đã duyệt',
        statusColor: 'success',
        relativeTime: '6 ngày trước',
        timestamp: '28/06/2026 11:30',
      },
      {
        id: 'w3',
        title: 'HR duyệt',
        person: 'Đỗ Thanh Tâm',
        personAvatar: avatar('Đỗ Thanh Tâm'),
        status: 'done',
        statusLabel: 'Đã duyệt',
        statusColor: 'success',
        relativeTime: '5 ngày trước',
        timestamp: '30/06/2026 08:45',
      },
      {
        id: 'w4',
        title: 'Hoàn tất',
        person: 'Hệ thống',
        personAvatar: '',
        status: 'done',
        statusLabel: 'Hoàn tất',
        statusColor: 'success',
        relativeTime: '5 ngày trước',
        timestamp: '30/06/2026 08:46',
      },
    ],
  },
  {
    id: '4',
    title: 'Frontend Developer',
    department: 'Engineering',
    level: 'Mid-level',
    count: 3,
    status: 'pending',
    requesterName: 'Phạm Hương Lan',
    requesterAvatar: avatar('Phạm Hương Lan'),
    requestDate: '02/07/2026',
  },
  {
    id: '5',
    title: 'Data Analyst',
    department: 'Data',
    level: 'Senior',
    count: 1,
    status: 'pending',
    requesterName: 'Hoàng Đức Anh',
    requesterAvatar: avatar('Hoàng Đức Anh'),
    requestDate: '30/06/2026',
  },
  {
    id: '6',
    title: 'HR Business Partner',
    department: 'Human Resources',
    level: 'Lead',
    count: 1,
    status: 'cc',
    requesterName: 'Đỗ Thanh Tâm',
    requesterAvatar: avatar('Đỗ Thanh Tâm'),
    requestDate: '25/06/2026',
  },
  {
    id: '7',
    title: 'DevOps Engineer',
    department: 'Engineering',
    level: 'Senior',
    count: 2,
    status: 'rejected',
    requesterName: 'Vũ Minh Tuấn',
    requesterAvatar: avatar('Vũ Minh Tuấn'),
    requestDate: '20/06/2026',
  },
]

export const departments = [
  'Tất cả phòng ban',
  'Engineering',
  'Product',
  'Design',
  'Quality Assurance',
  'Data',
  'Human Resources',
  'Marketing',
  'Finance',
]

// ============================================
// Mock Candidates — tied to job orders
// ============================================

export const mockCandidates: Candidate[] = [
  // === Backend Developer (job 1) — 8 candidates ===
  {
    id: 'c-101',
    jobOrderId: '1',
    name: 'Đặng Minh Quân',
    avatar: avatar('Đặng Minh Quân'),
    email: 'quan.dang@example.com',
    phone: '0901 xxx xxx',
    currentTitle: 'Senior Backend Engineer',
    currentCompany: 'VNG Corporation',
    yearsOfExperience: 6,
    stage: 'interview',
    rating: 4.5,
    appliedDate: '05/07/2026',
    source: 'LinkedIn',
    skills: ['Node.js', 'PostgreSQL', 'Kubernetes', 'Redis'],
  },
  {
    id: 'c-102',
    jobOrderId: '1',
    name: 'Ngô Thị Hương',
    avatar: avatar('Ngô Thị Hương'),
    email: 'huong.ngo@example.com',
    phone: '0912 xxx xxx',
    currentTitle: 'Backend Developer',
    currentCompany: 'Tiki',
    yearsOfExperience: 4,
    stage: 'offer',
    rating: 4.0,
    appliedDate: '03/07/2026',
    source: 'Referral',
    skills: ['Go', 'gRPC', 'Kafka', 'AWS'],
  },
  {
    id: 'c-103',
    jobOrderId: '1',
    name: 'Phan Văn Khoa',
    avatar: avatar('Phan Văn Khoa'),
    email: 'khoa.phan@example.com',
    phone: '0938 xxx xxx',
    currentTitle: 'Software Engineer',
    currentCompany: 'FPT Software',
    yearsOfExperience: 5,
    stage: 'screening',
    rating: 3.5,
    appliedDate: '06/07/2026',
    source: 'TopCV',
    skills: ['Java', 'Spring Boot', 'PostgreSQL'],
  },
  {
    id: 'c-104',
    jobOrderId: '1',
    name: 'Lý Thanh Tú',
    avatar: avatar('Lý Thanh Tú'),
    email: 'tu.ly@example.com',
    phone: '0945 xxx xxx',
    currentTitle: 'Backend Engineer',
    currentCompany: 'MoMo',
    yearsOfExperience: 4,
    stage: 'screening',
    rating: 4.0,
    appliedDate: '07/07/2026',
    source: 'Lark Form',
    skills: ['Node.js', 'TypeScript', 'MongoDB'],
  },
  {
    id: 'c-105',
    jobOrderId: '1',
    name: 'Võ Hải Yến',
    avatar: avatar('Võ Hải Yến'),
    email: 'yen.vo@example.com',
    phone: '0978 xxx xxx',
    currentTitle: 'Senior Software Engineer',
    currentCompany: 'ZaloPay',
    yearsOfExperience: 7,
    stage: 'applied',
    rating: 0,
    appliedDate: '08/07/2026',
    source: 'LinkedIn',
    skills: ['Go', 'Microservices', 'Kafka', 'gRPC'],
  },
  {
    id: 'c-106',
    jobOrderId: '1',
    name: 'Trịnh Đức Thành',
    avatar: avatar('Trịnh Đức Thành'),
    email: 'thanh.trinh@example.com',
    phone: '0903 xxx xxx',
    currentTitle: 'Tech Lead',
    currentCompany: 'VinAI',
    yearsOfExperience: 8,
    stage: 'rejected',
    rating: 3.0,
    appliedDate: '02/07/2026',
    source: 'Referral',
    skills: ['Python', 'Django', 'AWS'],
  },
  {
    id: 'c-107',
    jobOrderId: '1',
    name: 'Bùi Khánh Linh',
    avatar: avatar('Bùi Khánh Linh'),
    email: 'linh.bui@example.com',
    phone: '0966 xxx xxx',
    currentTitle: 'Backend Developer',
    currentCompany: 'Grab Vietnam',
    yearsOfExperience: 3,
    stage: 'hired',
    rating: 5.0,
    appliedDate: '01/07/2026',
    source: 'LinkedIn',
    skills: ['Node.js', 'GraphQL', 'PostgreSQL'],
  },
  {
    id: 'c-108',
    jobOrderId: '1',
    name: 'Đào Sơn Tùng',
    avatar: avatar('Đào Sơn Tùng'),
    email: 'tung.dao@example.com',
    phone: '0923 xxx xxx',
    currentTitle: 'Senior Engineer',
    currentCompany: 'Shopee',
    yearsOfExperience: 5,
    stage: 'interview',
    rating: 4.0,
    appliedDate: '04/07/2026',
    source: 'TopCV',
    skills: ['Java', 'Spring', 'Kafka'],
  },

  // === Product Designer (job 2) — 5 candidates ===
  {
    id: 'c-201',
    jobOrderId: '2',
    name: 'Hoàng Mai Chi',
    avatar: avatar('Hoàng Mai Chi'),
    email: 'chi.hoang@example.com',
    phone: '0911 xxx xxx',
    currentTitle: 'Product Designer',
    currentCompany: 'Be Group',
    yearsOfExperience: 4,
    stage: 'interview',
    rating: 4.5,
    appliedDate: '04/07/2026',
    source: 'LinkedIn',
    skills: ['Figma', 'Design System', 'Prototyping'],
  },
  {
    id: 'c-202',
    jobOrderId: '2',
    name: 'Nguyễn Phương Anh',
    avatar: avatar('Nguyễn Phương Anh'),
    email: 'anh.nguyen@example.com',
    phone: '0934 xxx xxx',
    currentTitle: 'UX Designer',
    currentCompany: 'VNLife',
    yearsOfExperience: 3,
    stage: 'screening',
    rating: 4.0,
    appliedDate: '06/07/2026',
    source: 'Referral',
    skills: ['Figma', 'User Research', 'Webflow'],
  },
  {
    id: 'c-203',
    jobOrderId: '2',
    name: 'Lê Quang Đạt',
    avatar: avatar('Lê Quang Đạt'),
    email: 'dat.le@example.com',
    phone: '0956 xxx xxx',
    currentTitle: 'Senior Designer',
    currentCompany: 'Tinh tế',
    yearsOfExperience: 6,
    stage: 'offer',
    rating: 5.0,
    appliedDate: '02/07/2026',
    source: 'LinkedIn',
    skills: ['Figma', 'Branding', 'Motion'],
  },
  {
    id: 'c-204',
    jobOrderId: '2',
    name: 'Trần Bảo Ngọc',
    avatar: avatar('Trần Bảo Ngọc'),
    email: 'ngoc.tran@example.com',
    phone: '0977 xxx xxx',
    currentTitle: 'UI Designer',
    currentCompany: 'Freelance',
    yearsOfExperience: 2,
    stage: 'applied',
    rating: 0,
    appliedDate: '08/07/2026',
    source: 'Lark Form',
    skills: ['Figma', 'Illustrator'],
  },
  {
    id: 'c-205',
    jobOrderId: '2',
    name: 'Phạm Minh Khôi',
    avatar: avatar('Phạm Minh Khôi'),
    email: 'khoi.pham@example.com',
    phone: '0988 xxx xxx',
    currentTitle: 'Product Designer',
    currentCompany: 'Lazada',
    yearsOfExperience: 5,
    stage: 'rejected',
    rating: 2.5,
    appliedDate: '01/07/2026',
    source: 'TopCV',
    skills: ['Figma', 'Sketch'],
  },

  // === QA Engineer (job 3) — 3 candidates ===
  {
    id: 'c-301',
    jobOrderId: '3',
    name: 'Đinh Thị Lan Anh',
    avatar: avatar('Đinh Thị Lan Anh'),
    email: 'lananh.dinh@example.com',
    phone: '0902 xxx xxx',
    currentTitle: 'Junior QA',
    currentCompany: 'NashTech',
    yearsOfExperience: 1,
    stage: 'screening',
    rating: 3.5,
    appliedDate: '03/07/2026',
    source: 'TopCV',
    skills: ['Manual Testing', 'Postman', 'SQL'],
  },
  {
    id: 'c-302',
    jobOrderId: '3',
    name: 'Cao Tiến Đạt',
    avatar: avatar('Cao Tiến Đạt'),
    email: 'dat.cao@example.com',
    phone: '0913 xxx xxx',
    currentTitle: 'Fresher',
    currentCompany: 'Newbie',
    yearsOfExperience: 0,
    stage: 'applied',
    rating: 0,
    appliedDate: '05/07/2026',
    source: 'Lark Form',
    skills: ['Manual Testing', 'JIRA'],
  },
  {
    id: 'c-303',
    jobOrderId: '3',
    name: 'Nguyễn Thị Thảo',
    avatar: avatar('Nguyễn Thị Thảo'),
    email: 'thao.nguyen@example.com',
    phone: '0944 xxx xxx',
    currentTitle: 'QA Engineer',
    currentCompany: 'Sendo',
    yearsOfExperience: 2,
    stage: 'interview',
    rating: 4.0,
    appliedDate: '02/07/2026',
    source: 'Referral',
    skills: ['Automation', 'Playwright', 'API Testing'],
  },
]

// ============================================
// Mock Comments — per job order
// ============================================

export const mockComments: Comment[] = [
  // ===== Backend Developer (job 1) — 5 entries =====
  {
    id: 'cm-1001',
    jobOrderId: '1',
    author: { kind: 'system', eventType: 'auto_cc', name: 'System' },
    content: 'Nguyễn Kiến Thức and Phan Trọng Khanh',
    mentions: [
      { name: 'Nguyễn Kiến Thức', userId: 'u-kienthuc' },
      { name: 'Phan Trọng Khanh', userId: 'u-trongkhanh' },
    ],
    readBy: ['Nguyễn Kiến Thức'],
    timestamp: '02/07/2026 16:18',
    relativeTime: '2 ngày trước',
  },
  {
    id: 'cm-1002',
    jobOrderId: '1',
    author: {
      kind: 'user',
      name: 'Kevin Hoang',
      avatar: avatar('Kevin Hoang'),
    },
    content: 'Hú',
    timestamp: '02/07/2026 16:33',
  },
  {
    id: 'cm-1003',
    jobOrderId: '1',
    author: {
      kind: 'user',
      name: 'Nguyễn Kiến Thức',
      avatar: avatar('Nguyễn Kiến Thức'),
    },
    content: 'Check mail em nhé',
    timestamp: '03/07/2026 09:27',
  },
  {
    id: 'cm-1004',
    jobOrderId: '1',
    author: {
      kind: 'user',
      name: 'Kevin Hoang',
      avatar: avatar('Kevin Hoang'),
    },
    content: '🥂',
    timestamp: '03/07/2026 09:38',
  },
  {
    id: 'cm-1005',
    jobOrderId: '1',
    author: {
      kind: 'user',
      name: 'Kevin Hoang',
      avatar: avatar('Kevin Hoang'),
    },
    content: 'Da thanks anh',
    timestamp: '03/07/2026 09:38',
  },

  // ===== Product Designer (job 2) — 2 entries =====
  {
    id: 'cm-2001',
    jobOrderId: '2',
    author: {
      kind: 'user',
      name: 'Lê Khánh Vy',
      avatar: avatar('Lê Khánh Vy'),
    },
    content: 'JD đã update phần portfolio requirements. Mọi người review lại nhé.',
    timestamp: '02/07/2026 11:24',
  },
  {
    id: 'cm-2002',
    jobOrderId: '2',
    author: {
      kind: 'user',
      name: 'Trần Thị Mai',
      avatar: avatar('Trần Thị Mai'),
    },
    content: 'Ok bạn, em sẽ update lại JD trong hôm nay.',
    timestamp: '02/07/2026 13:50',
  },
]