import type { JobOrder } from '@/types/recruitment'

// Mock job orders data matching the Stitch design
export const mockJobOrders: JobOrder[] = [
  {
    id: '1',
    title: 'Backend Developer',
    department: 'Engineering',
    level: 'Senior',
    count: 2,
    status: 'approved',
    requesterName: 'Nguyễn Văn An',
    requesterAvatar: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDWxQh5AS7soorhzNgCU5f3hXZbp9AJrH6-dd-HXvax5SYNczT7_8QwSKTeaZCtbA-yhGOAzkxi_uLzM5u0VxKJf5kVh3SMTZ9BgXwytYHzXQMHaFbVF3M0Zp_-ijwzSu5BMokFxgi2TkarzXaO1e783HRlPXv5KfhaCebF9buD8RFIWvFM5fvQAXGFjITZLV_y8X0w4klo2CBiS3W7K-w-unU6Fn5LynOFUIWQ2IuqB59c4OADM3HyXENdaNJQueAm4LBuXoBYfQI',
    requestDate: '03/07/2026',
  },
  {
    id: '2',
    title: 'Product Designer',
    department: 'Product',
    level: 'Mid-level',
    count: 1,
    status: 'approved',
    requesterName: 'Trần Thị Mai',
    requesterAvatar: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBSMRmhDYth2c6BCuFanwhEauTNF7Ebroo4XRvdAGbzDTIuk6R2vHqwCZpyspjTGWB26aq1e9aNn6sCd4tZ-NjjfWk1dXleEsLKhKdK2TE5KFUER8rbn5l9h3nVpOV39LWVc0j2AC77dx3-BPnwvoQ8pBIeIrs_TfwgLAkIf1ZonbR9ZyYL9z8BobO-2RIYIQh5yP927hFw1VjYGjMYkUVxO4K3oO7JmUqY7aci8zboNShZewPkKx8z2SNU6HKRZNBrLShExE52SjE',
    requestDate: '01/07/2026',
  },
  {
    id: '3',
    title: 'QA Engineer',
    department: 'Quality Assurance',
    level: 'Junior',
    count: 1,
    status: 'approved',
    requesterName: 'Lê Minh Đức',
    requesterAvatar: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAAonWV2EzDZ7yrXCZ3ciIP3sRsczk2LS9QibwwlCn7UzcSUXGLzETsUKQwoS98j7dxK4TeVncXboIpa1MdoeR64-gRHRE-94GxBo59qOrfKigzD24lr8t4c1ucqsqbZK8tyE4c7OdXtuJQ-uIL6vmvqxSj__PBz4GYmt26gtE6b96r-NwY-afaM9od8ZDu5KTIdlscp740uc-siF7waITsOZABZm0EYK3vCcxzFYIBxHucDEho3YB9fpcsdWCz7jHdVazVTrEaMcE',
    requestDate: '28/06/2026',
  },
  // Additional mock data for other tabs
  {
    id: '4',
    title: 'Frontend Developer',
    department: 'Engineering',
    level: 'Mid-level',
    count: 3,
    status: 'pending',
    requesterName: 'Phạm Hương Lan',
    requesterAvatar: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDWxQh5AS7soorhzNgCU5f3hXZbp9AJrH6-dd-HXvax5SYNczT7_8QwSKTeaZCtbA-yhGOAzkxi_uLzM5u0VxKJf5kVh3SMTZ9BgXwytYHzXQMHaFbVF3M0Zp_-ijwzSu5BMokFxgi2TkarzXaO1e783HRlPXv5KfhaCebF9buD8RFIWvFM5fvQAXGFjITZLV_y8X0w4klo2CBiS3W7K-w-unU6Fn5LynOFUIWQ2IuqB59c4OADM3HyXENdaNJQueAm4LBuXoBYfQI',
    requestDate: '02/07/2026',
  },
  {
    id: '5',
    title: 'Data Analyst',
    department: 'Data',
    level: 'Senior',
    count: 1,
    status: 'pending',
    requesterName: 'Hoàng Đức Anh',
    requesterAvatar: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBSMRmhDYth2c6BCuFanwhEauTNF7Ebroo4XRvdAGbzDTIuk6R2vHqwCZpyspjTGWB26aq1e9aNn6sCd4tZ-NjjfWk1dXleEsLKhKdK2TE5KFUER8rbn5l9h3nVpOV39LWVc0j2AC77dx3-BPnwvoQ8pBIeIrs_TfwgLAkIf1ZonbR9ZyYL9z8BobO-2RIYIQh5yP927hFw1VjYGjMYkUVxO4K3oO7JmUqY7aci8zboNShZewPkKx8z2SNU6HKRZNBrLShExE52SjE',
    requestDate: '30/06/2026',
  },
  {
    id: '6',
    title: 'HR Business Partner',
    department: 'Human Resources',
    level: 'Lead',
    count: 1,
    status: 'cc',
    requesterName: 'Đỗ Thanh Tâm',
    requesterAvatar: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAAonWV2EzDZ7yrXCZ3ciIP3sRsczk2LS9QibwwlCn7UzcSUXGLzETsUKQwoS98j7dxK4TeVncXboIpa1MdoeR64-gRHRE-94GxBo59qOrfKigzD24lr8t4c1ucqsqbZK8tyE4c7OdXtuJQ-uIL6vmvqxSj__PBz4GYmt26gtE6b96r-NwY-afaM9od8ZDu5KTIdlscp740uc-siF7waITsOZABZm0EYK3vCcxzFYIBxHucDEho3YB9fpcsdWCz7jHdVazVTrEaMcE',
    requestDate: '25/06/2026',
  },
  {
    id: '7',
    title: 'DevOps Engineer',
    department: 'Engineering',
    level: 'Senior',
    count: 2,
    status: 'rejected',
    requesterName: 'Vũ Minh Tuấn',
    requesterAvatar: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDWxQh5AS7soorhzNgCU5f3hXZbp9AJrH6-dd-HXvax5SYNczT7_8QwSKTeaZCtbA-yhGOAzkxi_uLzM5u0VxKJf5kVh3SMTZ9BgXwytYHzXQMHaFbVF3M0Zp_-ijwzSu5BMokFxgi2TkarzXaO1e783HRlPXv5KfhaCebF9buD8RFIWvFM5fvQAXGFjITZLV_y8X0w4klo2CBiS3W7K-w-unU6Fn5LynOFUIWQ2IuqB59c4OADM3HyXENdaNJQueAm4LBuXoBYfQI',
    requestDate: '20/06/2026',
  },
]

export const departments = [
  'Tất cả phòng ban',
  'Engineering',
  'Product',
  'Design',
  'Quality Assurance',
  'Data',
  'Human Resources',
  'Marketing',
  'Finance',
]
