/**
 * Hiring Management Hub - Lark Workplace Block
 * App entry point + shared mock data
 */

// Use UI Avatars API as fallback (initials-based avatars)
function avatar(name) {
  return `https://ui-avatars.com/api/?name=${encodeURIComponent(name)}&background=303030&color=fff&bold=true&size=128`
}

// ============================================
// Mock Job Orders (extended with detail fields)
// ============================================
const MOCK_JOB_ORDERS = [
  {
    id: '1',
    title: 'Backend Developer',
    department: 'Engineering',
    level: 'Senior',
    count: 2,
    status: 'approved',
    statusLabel: 'Đã duyệt',
    requestCode: 'REQ-20260703-001',
    requesterName: 'Nguyễn Văn An',
    requesterAvatar: avatar('Nguyễn Văn An'),
    requestDate: '03/07/2026',
    requestTime: '16:57',
    recruitmentReason:
      'Mở rộng đội ngũ phát triển sản phẩm mới nhằm phục vụ thị trường Đông Nam Á.',
    requiredSkills: ['Java', 'Spring Boot', 'PostgreSQL', 'AWS'],
    workArrangement: 'Hybrid (3 ngày tại văn phòng)',
    budget: '30 - 45 triệu/tháng',
    hiringManager: {
      name: 'Phạm Quang Hải',
      title: 'Phó giám đốc kỹ thuật',
      avatar: avatar('Phạm Quang Hải'),
    },
    deadline: '31/07/2026',
    workflow: [
      {
        id: 'w1',
        title: 'Tạo yêu cầu',
        person: 'Nguyễn Văn An',
        status: 'done',
        statusLabel: 'Đã gửi',
        statusColor: 'success',
        relativeTime: '1 ngày trước',
        timestamp: '03/07/2026 16:53',
      },
      {
        id: 'w2',
        title: 'Trưởng bộ phận duyệt',
        person: 'Kevin Hoang',
        status: 'done',
        statusLabel: 'Đã duyệt',
        statusColor: 'success',
        relativeTime: '1 ngày trước',
        timestamp: '03/07/2026 16:57',
      },
      {
        id: 'w3',
        title: 'HR duyệt',
        person: 'Trần Thị Mai',
        status: 'active',
        statusLabel: 'Đang chờ',
        statusColor: 'active',
        relativeTime: 'Hôm nay',
      },
      {
        id: 'w4',
        title: 'Hoàn tất',
        person: 'Hệ thống',
        status: 'pending',
        statusLabel: '',
        statusColor: 'outline',
      },
    ],
  },
  {
    id: '2',
    title: 'Product Designer',
    department: 'Product',
    level: 'Mid-level',
    count: 1,
    status: 'approved',
    statusLabel: 'Đã duyệt',
    requestCode: 'REQ-20260701-002',
    requesterName: 'Trần Thị Mai',
    requesterAvatar: avatar('Trần Thị Mai'),
    requestDate: '01/07/2026',
    requestTime: '10:24',
    recruitmentReason:
      'Cần bổ sung Product Designer để dẫn dắt thiết kế cho dòng sản phẩm B2B mới ra mắt Q3.',
    requiredSkills: ['Figma', 'Design System', 'Prototyping', 'User Research'],
    workArrangement: 'Hybrid (2 ngày tại văn phòng)',
    budget: '25 - 35 triệu/tháng',
    hiringManager: {
      name: 'Lê Khánh Vy',
      title: 'Head of Product',
      avatar: avatar('Lê Khánh Vy'),
    },
    deadline: '15/07/2026',
    workflow: [
      {
        id: 'w1',
        title: 'Tạo yêu cầu',
        person: 'Trần Thị Mai',
        status: 'done',
        statusLabel: 'Đã gửi',
        statusColor: 'success',
        relativeTime: '3 ngày trước',
        timestamp: '01/07/2026 10:24',
      },
      {
        id: 'w2',
        title: 'Trưởng bộ phận duyệt',
        person: 'Phạm Quang Hải',
        status: 'done',
        statusLabel: 'Đã duyệt',
        statusColor: 'success',
        relativeTime: '3 ngày trước',
        timestamp: '01/07/2026 14:08',
      },
      {
        id: 'w3',
        title: 'HR duyệt',
        person: 'Đỗ Thanh Tâm',
        status: 'done',
        statusLabel: 'Đã duyệt',
        statusColor: 'success',
        relativeTime: '3 ngày trước',
        timestamp: '02/07/2026 09:15',
      },
      {
        id: 'w4',
        title: 'Hoàn tất',
        person: 'Hệ thống',
        status: 'done',
        statusLabel: 'Hoàn tất',
        statusColor: 'success',
        relativeTime: '2 ngày trước',
        timestamp: '02/07/2026 09:16',
      },
    ],
  },
  {
    id: '3',
    title: 'QA Engineer',
    department: 'Quality Assurance',
    level: 'Junior',
    count: 1,
    status: 'approved',
    statusLabel: 'Đã duyệt',
    requestCode: 'REQ-20260628-003',
    requesterName: 'Lê Minh Đức',
    requesterAvatar: avatar('Lê Minh Đức'),
    requestDate: '28/06/2026',
    requestTime: '09:12',
    recruitmentReason:
      'Tăng cường đội ngũ QA cho dự án automation testing phase 2.',
    requiredSkills: ['Manual Testing', 'API Testing', 'SQL'],
    workArrangement: 'Onsite (tại văn phòng Đà Nẵng)',
    budget: '12 - 18 triệu/tháng',
    hiringManager: {
      name: 'Phạm Thanh Hà',
      title: 'QA Lead',
      avatar: avatar('Phạm Thanh Hà'),
    },
    deadline: '20/07/2026',
    workflow: [
      {
        id: 'w1',
        title: 'Tạo yêu cầu',
        person: 'Lê Minh Đức',
        status: 'done',
        statusLabel: 'Đã gửi',
        statusColor: 'success',
        relativeTime: '6 ngày trước',
        timestamp: '28/06/2026 09:12',
      },
      {
        id: 'w2',
        title: 'Trưởng bộ phận duyệt',
        person: 'Phạm Thanh Hà',
        status: 'done',
        statusLabel: 'Đã duyệt',
        statusColor: 'success',
        relativeTime: '6 ngày trước',
        timestamp: '28/06/2026 11:30',
      },
      {
        id: 'w3',
        title: 'HR duyệt',
        person: 'Đỗ Thanh Tâm',
        status: 'done',
        statusLabel: 'Đã duyệt',
        statusColor: 'success',
        relativeTime: '5 ngày trước',
        timestamp: '30/06/2026 08:45',
      },
      {
        id: 'w4',
        title: 'Hoàn tất',
        person: 'Hệ thống',
        status: 'done',
        statusLabel: 'Hoàn tất',
        statusColor: 'success',
        relativeTime: '5 ngày trước',
        timestamp: '30/06/2026 08:46',
      },
    ],
  },
]

// ============================================
// Mock Candidates
// ============================================
const MOCK_CANDIDATES = [
  // Backend Developer (job 1) — 8 candidates
  {
    id: 'c-101',
    jobOrderId: '1',
    name: 'Đặng Minh Quân',
    avatar: avatar('Đặng Minh Quân'),
    email: 'quan.dang@example.com',
    currentTitle: 'Senior Backend Engineer',
    currentCompany: 'VNG Corporation',
    yearsOfExperience: 6,
    stage: 'interview',
    rating: 4.5,
    appliedDate: '05/07/2026',
    source: 'LinkedIn',
    skills: ['Node.js', 'PostgreSQL', 'Kubernetes', 'Redis'],
  },
  {
    id: 'c-102',
    jobOrderId: '1',
    name: 'Ngô Thị Hương',
    avatar: avatar('Ngô Thị Hương'),
    email: 'huong.ngo@example.com',
    currentTitle: 'Backend Developer',
    currentCompany: 'Tiki',
    yearsOfExperience: 4,
    stage: 'offer',
    rating: 4.0,
    appliedDate: '03/07/2026',
    source: 'Referral',
    skills: ['Go', 'gRPC', 'Kafka', 'AWS'],
  },
  {
    id: 'c-103',
    jobOrderId: '1',
    name: 'Phan Văn Khoa',
    avatar: avatar('Phan Văn Khoa'),
    email: 'khoa.phan@example.com',
    currentTitle: 'Software Engineer',
    currentCompany: 'FPT Software',
    yearsOfExperience: 5,
    stage: 'screening',
    rating: 3.5,
    appliedDate: '06/07/2026',
    source: 'TopCV',
    skills: ['Java', 'Spring Boot', 'PostgreSQL'],
  },
  {
    id: 'c-104',
    jobOrderId: '1',
    name: 'Lý Thanh Tú',
    avatar: avatar('Lý Thanh Tú'),
    email: 'tu.ly@example.com',
    currentTitle: 'Backend Engineer',
    currentCompany: 'MoMo',
    yearsOfExperience: 4,
    stage: 'screening',
    rating: 4.0,
    appliedDate: '07/07/2026',
    source: 'Lark Form',
    skills: ['Node.js', 'TypeScript', 'MongoDB'],
  },
  {
    id: 'c-105',
    jobOrderId: '1',
    name: 'Võ Hải Yến',
    avatar: avatar('Võ Hải Yến'),
    email: 'yen.vo@example.com',
    currentTitle: 'Senior Software Engineer',
    currentCompany: 'ZaloPay',
    yearsOfExperience: 7,
    stage: 'applied',
    rating: 0,
    appliedDate: '08/07/2026',
    source: 'LinkedIn',
    skills: ['Go', 'Microservices', 'Kafka', 'gRPC'],
  },
  {
    id: 'c-106',
    jobOrderId: '1',
    name: 'Trịnh Đức Thành',
    avatar: avatar('Trịnh Đức Thành'),
    email: 'thanh.trinh@example.com',
    currentTitle: 'Tech Lead',
    currentCompany: 'VinAI',
    yearsOfExperience: 8,
    stage: 'rejected',
    rating: 3.0,
    appliedDate: '02/07/2026',
    source: 'Referral',
    skills: ['Python', 'Django', 'AWS'],
  },
  {
    id: 'c-107',
    jobOrderId: '1',
    name: 'Bùi Khánh Linh',
    avatar: avatar('Bùi Khánh Linh'),
    email: 'linh.bui@example.com',
    currentTitle: 'Backend Developer',
    currentCompany: 'Grab Vietnam',
    yearsOfExperience: 3,
    stage: 'hired',
    rating: 5.0,
    appliedDate: '01/07/2026',
    source: 'LinkedIn',
    skills: ['Node.js', 'GraphQL', 'PostgreSQL'],
  },
  {
    id: 'c-108',
    jobOrderId: '1',
    name: 'Đào Sơn Tùng',
    avatar: avatar('Đào Sơn Tùng'),
    email: 'tung.dao@example.com',
    currentTitle: 'Senior Engineer',
    currentCompany: 'Shopee',
    yearsOfExperience: 5,
    stage: 'interview',
    rating: 4.0,
    appliedDate: '04/07/2026',
    source: 'TopCV',
    skills: ['Java', 'Spring', 'Kafka'],
  },

  // Product Designer (job 2) — 5 candidates
  {
    id: 'c-201',
    jobOrderId: '2',
    name: 'Lê Thị Mai Anh',
    avatar: avatar('Lê Thị Mai Anh'),
    email: 'maianh.le@example.com',
    currentTitle: 'Backend Developer',
    currentCompany: 'Be Group',
    yearsOfExperience: 4,
    stage: 'interview',
    rating: 4.5,
    appliedDate: '04/07/2026',
    source: 'LinkedIn',
    skills: ['Figma', 'Design System', 'Prototyping'],
  },
  {
    id: 'c-202',
    jobOrderId: '2',
    name: 'Trần Minh Quân',
    avatar: avatar('Trần Minh Quân'),
    email: 'quan.tran@example.com',
    currentTitle: 'Product Designer',
    currentCompany: 'VNLife',
    yearsOfExperience: 3,
    stage: 'screening',
    rating: 4.0,
    appliedDate: '06/07/2026',
    source: 'Referral',
    skills: ['Figma', 'User Research', 'Webflow'],
  },
  {
    id: 'c-203',
    jobOrderId: '2',
    name: 'Phạm Thu Hương',
    avatar: avatar('Phạm Thu Hương'),
    email: 'huong.pham@example.com',
    currentTitle: 'Marketing Specialist',
    currentCompany: 'Tinh tế',
    yearsOfExperience: 6,
    stage: 'offer',
    rating: 5.0,
    appliedDate: '02/07/2026',
    source: 'LinkedIn',
    skills: ['Figma', 'Branding', 'Motion'],
  },
  {
    id: 'c-204',
    jobOrderId: '2',
    name: 'Nguyễn Hoàng Nam',
    avatar: avatar('Nguyễn Hoàng Nam'),
    email: 'nam.nguyen@example.com',
    currentTitle: 'QA Engineer',
    currentCompany: 'Lazada',
    yearsOfExperience: 5,
    stage: 'rejected',
    rating: 2.5,
    appliedDate: '01/07/2026',
    source: 'TopCV',
    skills: ['Figma', 'Sketch'],
  },
  {
    id: 'c-205',
    jobOrderId: '2',
    name: 'Đỗ Thanh Tâm',
    avatar: avatar('Đỗ Thanh Tâm'),
    email: 'tam.do@example.com',
    currentTitle: 'UI Designer',
    currentCompany: 'Freelance',
    yearsOfExperience: 2,
    stage: 'applied',
    rating: 0,
    appliedDate: '08/07/2026',
    source: 'Lark Form',
    skills: ['Figma', 'Illustrator'],
  },

  // QA Engineer (job 3) — 3 candidates
  {
    id: 'c-301',
    jobOrderId: '3',
    name: 'Đinh Thị Lan Anh',
    avatar: avatar('Đinh Thị Lan Anh'),
    email: 'lananh.dinh@example.com',
    currentTitle: 'Junior QA',
    currentCompany: 'NashTech',
    yearsOfExperience: 1,
    stage: 'screening',
    rating: 3.5,
    appliedDate: '03/07/2026',
    source: 'TopCV',
    skills: ['Manual Testing', 'Postman', 'SQL'],
  },
  {
    id: 'c-302',
    jobOrderId: '3',
    name: 'Cao Tiến Đạt',
    avatar: avatar('Cao Tiến Đạt'),
    email: 'dat.cao@example.com',
    currentTitle: 'Fresher',
    currentCompany: 'Newbie',
    yearsOfExperience: 0,
    stage: 'applied',
    rating: 0,
    appliedDate: '05/07/2026',
    source: 'Lark Form',
    skills: ['Manual Testing', 'JIRA'],
  },
  {
    id: 'c-303',
    jobOrderId: '3',
    name: 'Nguyễn Thị Thảo',
    avatar: avatar('Nguyễn Thị Thảo'),
    email: 'thao.nguyen@example.com',
    currentTitle: 'QA Engineer',
    currentCompany: 'Sendo',
    yearsOfExperience: 2,
    stage: 'interview',
    rating: 4.0,
    appliedDate: '02/07/2026',
    source: 'Referral',
    skills: ['Automation', 'Playwright', 'API Testing'],
  },
]

// ============================================
// Helpers exposed via globalData
// ============================================
function getJobOrderById(id) {
  return MOCK_JOB_ORDERS.find(j => j.id === String(id)) || null
}

function getCandidatesByJobId(jobOrderId, stage) {
  let list = MOCK_CANDIDATES.filter(c => c.jobOrderId === String(jobOrderId))
  if (stage && stage !== 'all') {
    list = list.filter(c => c.stage === stage)
  }
  return list
}

function summarizeCandidateStages(jobOrderId) {
  const summary = {
    applied: 0,
    screening: 0,
    interview: 0,
    offer: 0,
    hired: 0,
    rejected: 0,
    total: 0,
  }
  for (const c of MOCK_CANDIDATES) {
    if (c.jobOrderId === String(jobOrderId)) {
      summary[c.stage]++
      summary.total++
    }
  }
  return summary
}

App({
  onLaunch() {
    console.log('[HRM Block] App launched')
  },

  globalData: {
    appID: 'cli_a92ec64c69b8ded1',
    blockTypeID: 'blk_69a47a51c8800ede6d63de15',
    MOCK_JOB_ORDERS,
    MOCK_CANDIDATES,
    getJobOrderById,
    getCandidatesByJobId,
    summarizeCandidateStages,
  },
})